version: '3.8'

services:
  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai-finance-server
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 5000
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
    ports:
      - "5000:5000"
    networks:
      - ai-finance-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/test', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ai-finance-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - ai-finance-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ai-finance-network:
    driver: bridge
